name: Ratchet Pinning/Unpinning

on:
  workflow_dispatch:

jobs:
  pin-check-job:
    runs-on: 'ubuntu-latest'
    name: 'ratchet'
    steps:
      - uses: 'actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b' # ratchet:actions/checkout@v3

      # Pinning
      - uses: 'docker://ghcr.io/sethvargo/ratchet:0.2.3'
        name: alerts.yaml - pinning
        with:
          args: "pin .github/workflows/alerts.yaml"

      # Checking versions are pinned.
      - uses: 'docker://ghcr.io/sethvargo/ratchet:0.2.3'
        name: alerts.yaml - checking versions are pinned
        with:
          args: 'check .github/workflows/alerts.yaml.yaml'

      # Pinning
      - uses: 'docker://ghcr.io/sethvargo/ratchet:0.2.3'
        name: build-and-deploy.yaml - pinning
        with:
          args: "pin .github/workflows/build-and-deploy.yaml"

      # Checking versions are pinned.
      - uses: 'docker://ghcr.io/sethvargo/ratchet:0.2.3'
        name: build-and-deploy.yaml - checking versions are pinned
        with:
          args: 'check .github/workflows/build-and-deploy.yaml'

      # Pinning
      - uses: 'docker://ghcr.io/sethvargo/ratchet:0.2.3'
        name: build-pr.yaml - pinning
        with:
          args: "pin .github/workflows/build-pr.yaml"

      # Checking versions are pinned.
      - uses: 'docker://ghcr.io/sethvargo/ratchet:0.2.3'
        name: build-pr.yaml - checking versions are pinned
        with:
          args: 'check .github/workflows/build-pr.yaml'

      # Pinning
      - uses: 'docker://ghcr.io/sethvargo/ratchet:0.2.3'
        name: snyk.yaml - pinning
        with:
          args: "pin .github/workflows/snyk.yaml"

      # Checking versions are pinned.
      - uses: 'docker://ghcr.io/sethvargo/ratchet:0.2.3'
        name: snyk.yaml - checking versions are pinned
        with:
          args: 'check .github/workflows/snyk.yaml'